version: '2'
services:
    attendance-app:
        image: attendance
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://attendance-postgresql:5432/Attendance
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    attendance-postgresql:
        extends:
            file: postgresql.yml
            service: attendance-postgresql
